/*
 Navicat MySQL Data Transfer

 Source Server         : 192.168.1.12
 Source Server Type    : MySQL
 Source Server Version : 80027
 Source Host           : 192.168.1.12:3306
 Source Schema         : epigram

 Target Server Type    : MySQL
 Target Server Version : 80027
 File Encoding         : 65001

 Date: 14/11/2021 00:11:04
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for epigram
-- ----------------------------
DROP TABLE IF EXISTS `epigram`;
CREATE TABLE `epigram`  (
  `id` bigint(0) NOT NULL,
  `content` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `created_at` datetime(6) NULL DEFAULT NULL,
  `updated_at` datetime(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of epigram
-- ----------------------------
INSERT INTO `epigram` VALUES (1, 'A man said to the Universe:\n	\"Sir, I exist!\"\n	\"However,\" replied the Universe,\n	\"the fact has not created in me a sense of obligation.\"\n		-- Stephen Crane', '2021-11-13 16:46:42.270000', NULL);
INSERT INTO `epigram` VALUES (2, 'A man who cannot seduce men cannot save them either.\n		-- Soren Kierkegaard', '2021-11-13 16:46:47.585000', '2021-11-13 23:30:49.698000');
INSERT INTO `epigram` VALUES (3, 'When beauty is abstracted\nThen ugliness has been implied;\nWhen good is abstracted\nThen evil has been implied.\nSo alive and dead are abstracted from nature,\nDifficult and easy abstracted from progress,\nLong and short abstracted from contrast,\nHigh and low abstracted from depth,\nSong and speech abstracted from melody,\nAfter and before abstracted from sequence.\nThe sage experiences without abstraction,\nAnd accomplishes without action;\nHe accepts the ebb and flow of things,\nNurtures them, but does not own them,\nAnd lives, but does not dwell.\n		-- Lao Tse, \"Tao Te Ching\"', '2021-11-13 16:47:03.829000', '2021-11-13 22:12:30.577000');
INSERT INTO `epigram` VALUES (4, 'You get along very well with everyone except animals and people.', '2021-11-13 16:47:12.790000', NULL);
INSERT INTO `epigram` VALUES (5, 'A career is great, but you can\'t run your fingers through its hair.', '2021-11-14 00:02:06.094959', NULL);
INSERT INTO `epigram` VALUES (6, 'A kiss is a course of procedure, cunningly devised, for the mutual\nstoppage of speech at a moment when words are superfluous.', '2021-11-14 00:02:06.094959', NULL);
INSERT INTO `epigram` VALUES (7, 'A woman was in love with fourteen soldiers.  It was clearly platoonic.', '2021-11-14 00:02:06.094959', NULL);
INSERT INTO `epigram` VALUES (8, 'Absence diminishes mediocre passions and increases great ones,\nas the wind blows out candles and fans fires.\n		-- La Rochefoucauld', '2021-11-14 00:02:06.094959', NULL);
INSERT INTO `epigram` VALUES (9, 'Absence in love is like water upon fire; a little quickens, but much\nextinguishes it.\n		-- Hannah More', '2021-11-14 00:03:05.382876', NULL);
INSERT INTO `epigram` VALUES (10, 'All the passions make us commit faults; love makes us commit the most\nridiculous ones.\n		-- La Rochefoucauld', '2021-11-14 00:03:05.382876', NULL);
INSERT INTO `epigram` VALUES (11, 'Always there remain portions of our heart into which no one is able to enter,\ninvite them as we may.', '2021-11-14 00:03:05.382876', NULL);
INSERT INTO `epigram` VALUES (12, 'Bondage maybe, discipline never!\n		-- T.K.', '2021-11-14 00:03:05.382876', NULL);
INSERT INTO `epigram` VALUES (13, 'Distrust all those who love you extremely upon a very slight acquaintance\nand without any visible reason.\n		-- Lord Chesterfield', '2021-11-14 00:03:05.382876', NULL);
INSERT INTO `epigram` VALUES (14, 'Don\'t despair; your ideal lover is waiting for you around the corner.', '2021-11-14 00:03:05.382876', NULL);
INSERT INTO `epigram` VALUES (15, 'Falling in Love\n	When two people have been on enough dates, they generally fall in\nlove.  You can tell you\'re in love by the way you feel: your head becomes\nlight, your heart leaps within you, you feel like you\'re walking on air,\nand the whole world seems like a wonderful and happy place.  Unfortunately,\nthese are also the four warning signs of colon disease, so it\'s always a\ngood idea to check with your doctor.\n		-- Dave Barry', '2021-11-14 00:03:05.382876', NULL);
INSERT INTO `epigram` VALUES (16, 'Falling in love is a lot like dying.  You never get to do it enough to\nbecome good at it.', '2021-11-14 00:03:05.382876', NULL);
INSERT INTO `epigram` VALUES (17, 'Finish the sentence below in 25 words or less:\n\n	\"Love is what you feel just before you give someone a good ...\"\n\nMail your answer along with the top half of your supervisor to:\n\n	P.O. Box 35\n	Baffled Greek, Michigan', '2021-11-14 00:03:05.382876', NULL);
INSERT INTO `epigram` VALUES (18, 'Give me chastity and continence, but not just now.\n		-- St. Augustine', '2021-11-14 00:03:05.382876', NULL);
INSERT INTO `epigram` VALUES (19, 'God is love, but get it in writing.\n		-- Gypsy Rose Lee', '2021-11-14 00:03:05.382876', NULL);
INSERT INTO `epigram` VALUES (20, '\"He did decide, though, that with more time and a great deal of mental\neffort, he could probably turn the activity into an acceptable perversion.\"\n		-- Mick Farren, \"When Gravity Fails\"', '2021-11-14 00:03:05.382876', NULL);
INSERT INTO `epigram` VALUES (21, 'He who is in love with himself has at least this advantage -- he won\'t\nencounter many rivals.\n		-- Georg Lichtenberg, \"Aphorisms\"', '2021-11-14 00:03:05.382876', NULL);
INSERT INTO `epigram` VALUES (22, 'Hearts will never be practical until they can be made unbreakable.\n		-- The Wizard of Oz', '2021-11-14 00:03:05.382876', NULL);
INSERT INTO `epigram` VALUES (23, 'HEY KIDS!  ANN LANDERS SAYS:\n	Be sure it\'s true, when you say \"I love you\".  It\'s a sin to\n	tell a lie.  Millions of hearts have been broken, just because\n	these words were spoken.', '2021-11-14 00:03:05.382876', NULL);
INSERT INTO `epigram` VALUES (24, 'His heart was yours from the first moment that you met.', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (25, 'How much does she love you?  Less than you\'ll ever know.', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (26, 'I am two fools, I know, for loving, and for saying so.\n		-- John Donne', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (27, 'I can mend the break of day, heal a broken heart, and provide temporary\nrelief to nymphomaniacs.\n		-- Larry Lee', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (28, 'I don\'t want people to love me.  It makes for obligations.\n		-- Jean Anouilh', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (29, 'I love you more than anything in this world.  I don\'t expect that will last.\n		-- Elvis Costello', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (30, 'I love you, not only for what you are, but for what I am when I am with you.\n		-- Roy Croft', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (31, 'I loved her with a love thirsty and desperate. I felt that we two might commit\nsome act so atrocious that the world, seeing us, would find it irresistible.\n		-- Gene Wolfe, \"The Shadow of the Torturer\"', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (32, 'I never loved another person the way I loved myself.\n		-- Mae West', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (33, 'I think a relationship is like a shark.  It has to constantly move forward\nor it dies.  Well, what we have on our hands here is a dead shark.\n		-- Woody Allen', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (34, 'I used to be Snow White, but I drifted.\n		-- Mae West', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (35, 'I used to think romantic love was a neurosis shared by two, a supreme\nfoolishness.  I no longer thought that.  There\'s nothing foolish in\nloving anyone.  Thinking you\'ll be loved in return is what\'s foolish.\n		-- Rita Mae Brown', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (36, '\"I\'d love to go out with you, but I did my own thing and now I\'ve got\nto undo it.\"', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (37, '\"I\'d love to go out with you, but I have to floss my cat.\"', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (38, '\"I\'d love to go out with you, but I have to stay home and see if I snore.\"', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (39, '\"I\'d love to go out with you, but I never go out on days that end in `Y.\'\"', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (40, '\"I\'d love to go out with you, but I want to spend more time with my blender.\"', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (41, '\"I\'d love to go out with you, but I\'m attending the opening of my garage door.\"', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (42, '\"I\'d love to go out with you, but I\'m converting my calendar watch from\nJulian to Gregorian.\"', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (43, '\"I\'d love to go out with you, but I\'m doing door-to-door collecting for static\ncling.\"', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (44, '\"I\'d love to go out with you, but I\'m having all my plants neutered.\"', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (45, '\"I\'d love to go out with you, but I\'m staying home to work on my\ncottage cheese sculpture.\"', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (46, '\"I\'d love to go out with you, but I\'m taking punk totem pole carving.\"', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (47, '\"I\'d love to go out with you, but I\'ve been scheduled for a karma transplant.\"', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (48, '\"I\'d love to go out with you, but it\'s my parakeet\'s bowling night.\"', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (49, '\"I\'d love to go out with you, but my favorite commercial is on TV.\"', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (50, '\"I\'d love to go out with you, but the last time I went out, I never came back.\"', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (51, '\"I\'d love to go out with you, but the man on television told me to stay tuned.\"', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (52, '\"I\'d love to go out with you, but there are important world issues that\nneed worrying about.\"', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (53, 'I\'d love to kiss you, but I just washed my hair.\n		-- Bette Davis, \"Cabin in the Cotton\"', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (54, '\"I\'ll tell you what I know, then,\" he decided.  \"The pin I\'m wearing\nmeans I\'m a member of the IA.  That\'s Inamorati Anonymous.  An inamorato is\nsomebody in love.  That\'s the worst addiction of all.\"\n	\"Somebody is about to fall in love,\" Oedipa said, \"you go sit with\nthem, or something?\"\n	\"Right.  The whole idea is to get where you don\'t need it.  I was\nlucky.  I kicked it young.  But there are sixty-year-old men, believe it or\nnot, and women even older, who might wake up in the night screaming.\"\n	\"You hold meetings, then, like the AA?\"\n	\"No, of course not.  You get a phone number, an answering service\nyou can call.  Nobody knows anybody else\'s name; just the number in case\nit gets so bad you can\'t handle it alone.  We\'re isolates, Arnold.  Meetings\nwould destroy the whole point of it.\"\n		-- Thomas Pynchon, \"The Crying of Lot 49\"', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (55, 'If love is the answer, could you rephrase the question?\n		-- Lily Tomlin', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (56, 'If Love Were Oil, I\'d Be About A Quart Low\n		-- Book title by Lewis Grizzard', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (57, 'If only you knew she loved you, you could face the uncertainty of\nwhether you love her.', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (58, 'If you can\'t be good, be careful.  If you can\'t be careful, give me a call.', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (59, 'If you love someone, set them free.\nIf they don\'t come back, then call them up when you\'re drunk.', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (60, 'In a great romance, each person basically plays a part that the\nother really likes.\n		-- Elizabeth Ashley', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (61, 'In an age when the fashion is to be in love with yourself, confessing to\nbe in love with somebody else is an admission of unfaithfulness to one\'s\nbeloved.\n		-- Russell Baker', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (62, 'In love, she who gives her portrait promises the original.\n		-- Bruton', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (63, 'In real love you want the other person\'s good.  In romantic love you\nwant the other person.\n		-- Margaret Anderson', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (64, 'It is far better to be deceived than to be undeceived by those we love.', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (65, 'Just how difficult it is to write biography can be reckoned by anybody\nwho sits down and considers just how many people know the real truth\nabout his or her love affairs.\n		-- Rebecca West', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (66, 'Let us live!!!\nLet us love!!!\nLet us share the deepest secrets of our souls!!!\n\nYou first.', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (67, 'Let\'s just be friends and make no special effort to ever see each other again.', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (68, 'Let\'s not complicate our relationship by trying to communicate with each other.', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (69, 'Lonely is a man without love.\n		-- Engelbert Humperdinck', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (70, 'Love -- the last of the serious diseases of childhood.', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (71, 'Love and scandal are the best sweeteners of tea.', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (72, 'Love at first sight is one of the greatest labor-saving devices the\nworld has ever seen.', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (73, 'Love cannot be much younger than the lust for murder.\n		-- Sigmund Freud', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (74, 'Love conquers all things; let us too surrender to love.\n		-- Publius Vergilius Maro (Virgil)', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (75, 'Love is a grave mental disease.\n		-- Plato', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (76, 'Love is a snowmobile racing across the tundra, which suddenly flips\nover, pinning you underneath.  At night the ice weasels come.\n		-- Matt Groening, \"Love is Hell\"', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (77, 'Love is always open arms.  With arms open you allow love to come and\ngo as it wills, freely, for it will do so anyway.  If you close your\narms about love you\'ll find you are left only holding yourself.', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (78, 'Love is being stupid together.\n		-- Paul Valery', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (79, 'Love is dope, not chicken soup.  I mean, love is something to be passed\naround freely, not spooned down someone\'s throat for their own good by a\nJewish mother who cooked it all by herself.', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (80, 'Love is in the offing.\n		-- The Homicidal Maniac', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (81, 'Love is like a friendship caught on fire.  In the beginning a flame, very\npretty, often hot and fierce, but still only light and flickering.  As love\ngrows older, our hearts mature and our love becomes as coals, deep-burning\nand unquenchable.\n		-- Bruce Lee', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (82, 'Love is like the measles; we all have to go through it.\n		-- Jerome K. Jerome', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (83, 'Love is never asking why?', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (84, 'Love is not enough, but it sure helps.', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (85, 'Love is sentimental measles.', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (86, 'Love is staying up all night with a sick child, or a healthy adult.', '2021-11-14 00:03:05.386877', NULL);
INSERT INTO `epigram` VALUES (87, 'Love is the only game that is not called on account of darkness.\n		-- M. Hirschfield', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (88, 'Love is the process of my leading you gently back to yourself.\n		-- Saint Exupery', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (89, 'Love is the triumph of imagination over intelligence.\n		-- H. L. Mencken', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (90, 'Love IS what it\'s cracked up to be.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (91, 'Love is what you\'ve been through with somebody.\n		-- James Thurber', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (92, 'Love isn\'t only blind, it\'s also deaf, dumb, and stupid.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (93, 'Love means having to say you\'re sorry every five minutes.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (95, 'Love tells us many things that are not so.\n		-- Ukrainian Proverb', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (96, 'May your SO always know when you need a hug.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (97, '\"Maybe we should think of this as one perfect week... where we found each\nother, and loved each other... and then let each other go before anyone\nhad to seek professional help.\"', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (98, 'Most people don\'t need a great deal of love nearly so much as they need\na steady supply.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (99, 'My cup hath runneth\'d over with love.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (100, 'Nature abhors a virgin -- a frozen asset.\n		-- Clare Booth Luce', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (101, '\"No, I understand now,\" Auberon said, calm in the woods -- it was so\nsimple, really.  \"I didn\'t, for a long time, but I do now.  You just can\'t\nhold people, you can\'t own them.  I mean it\'s only natural, a natural process\nreally.  Meet.  Love.  Part.  Life goes on.  There was never any reason to\nexpect her to stay always the same -- I mean `in love,\' you know.\"  There were\nthose doubt-quotes of Smoky\'s, heavily indicated.  \"I don\'t hold a grudge.  I\ncan\'t.\"\n	\"You do,\" Grandfather Trout said.  \"And you don\'t understand.\"\n		-- Little, Big, \"John Crowley\"', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (102, 'Of all forms of caution, caution in love is the most fatal.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (103, 'Of course it\'s possible to love a human being if you don\'t know them too well.\n		-- Charles Bukowski', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (104, 'Oh, love is real enough, you will find it some day, but it has one\narch-enemy -- and that is life.\n		-- Jean Anouilh, \"Ardele\"', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (105, 'On a tous un peu peur de l\'amour, mais on a surtout peur de souffrir\nou de faire souffrir.\n	[One is always a little afraid of love, but above all, one is\n	 afraid of pain or causing pain.]', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (106, 'Once the realization is accepted that even between the closest human beings\ninfinite distances continue to exist, a wonderful living side by side can\ngrow up, if they succeed in loving the distance between them which makes it\npossible for each to see each other whole against the sky.\n		-- Rainer Rilke', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (107, 'One expresses well the love he does not feel.\n		-- J. A. Karr', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (108, 'People think love is an emotion.  Love is good sense.\n		-- Ken Kesey', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (109, 'Really??  What a coincidence, I\'m shallow too!!', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (110, 'Sometime when you least expect it, Love will tap you on the shoulder...\nand ask you to move out of the way because it still isn\'t your turn.\n		-- N. V. Plyter', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (111, 'Sometimes love ain\'t nothing but a misunderstanding between two fools.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (112, 'Sorry never means having your say to love.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (113, 'Speaking of love, one problem that recurs more and more frequently these\ndays, in books and plays and movies, is the inability of people to communicate\nwith the people they love; Husbands and wives who can\'t communicate, children\nwho can\'t communicate with their parents, and so on.  And the characters in\nthese books and plays and so on (and in real life, I might add) spend hours\nbemoaning the fact that they can\'t communicate.  I feel that if a person can\'t\ncommunicate, the very _____x08x08x08x08x08least he can do is to shut up!\n		-- Tom Lehrer, \"That Was the Year that Was\"', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (114, 'Support wildlife -- vote for an orgy.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (115, 'That is the true season of love, when we believe that we alone can love,\nthat no one could have loved so before us, and that no one will love\nin the same way as us.\n		-- Johann Wolfgang von Goethe', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (116, 'That\'s life for you, said McDunn.  Someone always waiting for someone who\nnever comes home.  Always someone loving something more than that thing loves\nthem.  And after awhile you want to destroy whatever that thing is, so it\ncan\'t hurt you no more.\n		-- R. Bradbury, \"The Fog Horn\"', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (117, 'The birds are singing, the flowers are budding, and it is time\nfor Miss Manners to tell young lovers to stop necking in public.\n	It\'s not that Miss Manners is immune to romance.  Miss Manners\nhas been known to squeeze a gentleman\'s arm while being helped over a\ncurb, and, in her wild youth, even to press a dainty slipper against a\nfoot or two under the dinner table.  Miss Manners also believes that the\nsight of people strolling hand in hand or arm in arm or arm in hand\ndresses up a city considerably more than the more familiar sight of\npeople shaking umbrellas at one another.  What Miss Manners objects to\nis the kind of activity that frightens the horses on the street...', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (118, 'The giraffe you thought you offended last week is willing to be nuzzled today.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (119, 'The heart has its reasons which reason knows nothing of.\n		-- Blaise Pascal', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (120, 'The heart is wiser than the intellect.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (121, 'The little pieces of my life I give to you, with love, to make a quilt\nto keep away the cold.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (122, 'The magic of our first love is our ignorance that it can ever end.\n		-- Benjamin Disraeli', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (123, 'The myth of romantic love holds that once you\'ve fallen in love with the\nperfect partner, you\'re home free.  Unfortunately, falling out of love\nseems to be just as involuntary as falling into it.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (124, 'The only difference in the game of love over the last few thousand years\nis that they\'ve changed trumps from clubs to diamonds.\n		-- The Indianapolis Star', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (125, 'The onset and the waning of love make themselves felt in the uneasiness\nexperienced at being alone together.\n		-- Jean de la Bruyere', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (126, 'The perfect lover is one who turns into a pizza at 4:00 A.M.\n		-- Charles Pierce', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (127, 'The person you rejected yesterday could make you happy, if you say yes.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (128, 'The seven year itch comes from fooling around during the fourth, fifth,\nand sixth years.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (129, 'The story of the butterfly:\n	\"I was in Bogota and waiting for a lady friend.  I was in love,\na long time ago.  I waited three days.  I was hungry but could not go\nout for food, lest she come and I not be there to greet her.  Then, on\nthe third day, I heard a knock.\"\n	\"I hurried along the old passage and there, in the sunlight,\nthere was nothing.\"\n	\"Just,\" Vance Joy said, \"a butterfly, flying away.\"\n		-- Peter Carey, BLISS', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (130, 'The sweeter the apple, the blacker the core --\nScratch a lover and find a foe!\n		-- Dorothy Parker, \"Ballad of a Great Weariness\"', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (131, 'The way to love anything is to realize that it might be lost.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (132, 'There are some micro-organisms that exhibit characteristics of both plants\nand animals.  When exposed to light they undergo photosynthesis; and when\nthe lights go out, they turn into animals.  But then again, don\'t we all?', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (133, 'There is no fear in love; but perfect love casts out fear.\n		-- 1 John 4:18', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (134, 'There is only one way to be happy by means of the heart -- to have none.\n		-- Paul Bourget', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (135, 'There\'s so much to say but your eyes keep interrupting me.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (136, 'Timing must be perfect now.  Two-timing must be better than perfect.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (137, 'To be loved is very demoralizing.\n		-- Katharine Hepburn', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (138, 'To fear love is to fear life, and those who fear life are already three\nparts dead.\n		-- Bertrand Russell', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (139, 'Total strangers need love, too; and I\'m stranger than most.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (140, 'True happiness will be found only in true love.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (141, 'Under deadline pressure for the next week.  If you want something, it can wait.\nUnless it\'s blind screaming paroxysmally hedonistic...', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (142, 'We don\'t believe in rheumatism and true love until after the first attack.\n		-- Marie Ebner von Eschenbach', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (143, 'What is irritating about love is that it is a crime that requires an accomplice.\n		-- Charles Baudelaire', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (144, 'When your life is a leaf that the seasons tear off and condemn\nThey will bind you with love that is graceful and green as a stem.\n		-- Leonard Cohen, \"Sisters of Mercy\"', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (145, 'Why I Can\'t Go Out With You:\n\nI\'d LOVE to, but ...\n	-- I have to floss my cat.\n	-- I\'ve dedicated my life to linguini.\n	-- I need to spend more time with my blender.\n	-- it wouldn\'t be fair to the other Beautiful People.\n	-- it\'s my night to pet the dog/ferret/goldfish.\n	-- I\'m going downtown to try on some gloves.\n	-- I have to check the freshness dates on my dairy products.\n	-- I\'m going down to the bakery to watch the buns rise.\n	-- I have an appointment with a cuticle specialist.\n	-- I have some really hard words to look up.\n	-- I\'ve got a Friends of the Lowly Rutabaga meeting.\n		-- I promised to help a friend fold road maps.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (146, 'Why I Can\'t Go Out With You:\n\nI\'d LOVE to, but...\n	-- I have to answer all of my \"occupant\" letters.\n	-- None of my socks match.\n	-- I\'m having all my plants neutered.\n	-- I changed the lock on my door and now I can\'t get out.\n	-- My yucca plant is feeling yucky.\n	-- I\'m touring China with a wok band.\n	-- My chocolate-appreciation class meets that night.\n	-- I\'m running off to Yugoslavia with a foreign-exchange student\n		named Basil Metabolism.\n	-- There are important world issues that need worrying about.\n	-- I\'m going to count the bristles in my toothbrush.\n	-- I prefer to remain an enigma.\n	-- I think you want the OTHER Peggy/Cathy/Mike/whomever.\n		-- I feel a song coming on.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (147, 'Why I Can\'t Go Out With You:\n\nI\'d LOVE to, but...\n	-- I have to draw \"Cubby\" for an art scholarship.\n	-- I have to sit up with a sick ant.\n	-- I\'m trying to be less popular.\n	-- My bathroom tiles need grouting.\n	-- I\'m waiting to see if I\'m already a winner.\n	-- My subconscious says no.\n	-- I just picked up a book called \"Glue in Many Lands\" and I\n		can\'t seem to put it down.\n	-- My favorite commercial is on TV.\n	-- I have to study for my blood test.\n	-- I\'ve been traded to Cincinnati.\n	-- I\'m having my baby shoes bronzed.\n		-- I have to go to court for kitty littering.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (148, 'Why I Can\'t Go Out With You:\n\nI\'d LOVE to, but...\n	-- I\'m trying to see how long I can go without saying yes.\n	-- I\'m attending the opening of my garage door.\n	-- The monsters haven\'t turned blue yet, and I have to eat more dots.\n	-- I\'m converting my calendar watch from Julian to Gregorian.\n	-- I have to fulfill my potential.\n	-- I don\'t want to leave my comfort zone.\n	-- It\'s too close to the turn of the century.\n	-- I have to bleach my hare.\n	-- I\'m worried about my vertical hold knob.\n		-- I left my body in my other clothes.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (149, 'Why I Can\'t Go Out With You:\n\nI\'d LOVE to, but...\n	-- I\'ve got a Friends of the Lowly Rutabaga meeting.\n	-- I promised to help a friend fold road maps.\n	-- I\'ve been scheduled for a karma transplant.\n	-- I\'m staying home to work on my cottage cheese sculpture.\n	-- It\'s my parakeet\'s bowling night.\n	-- I\'m building a plant from a kit.\n	-- There\'s a disturbance in the Force.\n	-- I\'m doing door-to-door collecting for static cling.\n	-- I\'m teaching my ferret to yodel.\n	-- My crayons all melted together.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (150, '\"Why must you tell me all your secrets when it\'s hard enough to love\nyou knowing nothing?\"\n		-- Lloyd Cole and the Commotions', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (151, 'Without love intelligence is dangerous;\nwithout intelligence love is not enough.\n		-- Ashley Montagu', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (152, 'Wouldn\'t this be a great world if being insecure and desperate were a turn-on?\n		-- \"Broadcast News\"', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (153, 'Yeah, there are more important things in life than money, but they won\'t go\nout with you if you don\'t have any.', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (154, 'You shouldn\'t have to pay for your love with your bones and your flesh.\n		-- Pat Benatar, \"Hell is for Children\"', '2021-11-14 00:03:05.388211', NULL);
INSERT INTO `epigram` VALUES (155, '1 + 1 = 3, for large values of 1.', '2021-11-14 00:05:54.763138', NULL);
INSERT INTO `epigram` VALUES (156, '1 Billion dollars of budget deficit		= 1 Gramm-Rudman\n6.023 x 10 to the 23rd power alligator pears	= Avocado\'s number\n2 pints						= 1 Cavort\nBasic unit of Laryngitis			= The Hoarsepower\nShortest distance between two jokes		= A straight line\n6 Curses					= 1 Hexahex\n3500 Calories					= 1 Food Pound\n1 Mole						= 007 Secret Agents\n1 Mole						= 25 Cagey Bees\n1 Dog Pound					= 16 oz. of Alpo\n1000 beers served at a Twins game		= 1 Killibrew\n2.4 statute miles of surgical tubing at Yale U. = 1 I.V.League\n2000 pounds of Chinese soup			= 1 Won Ton\n10 to the minus 6th power mouthwashes		= 1 Microscope\nSpeed of a tortoise breaking the sound barrier	= 1 Machturtle\n8 Catfish					= 1 Octo-puss\n365 Days of drinking Lo-Cal beer.		= 1 Lite-year\n16.5 feet in the Twilight Zone			= 1 Rod Serling\nForce needed to accelerate 2.2lbs of cookies	= 1 Fig-newton\n	to 1 meter per second\nOne half large intestine			= 1 Semicolon\n10 to the minus 6th power Movie			= 1 Microfilm\n1000 pains					= 1 Megahertz\n1 Word						= 1 Millipicture\n1 Sagan						= Billions & Billions\n1 Angstrom: measure of computer anxiety		= 1000 nail-bytes\n10 to the 12th power microphones		= 1 Megaphone\n10 to the 6th power Bicycles			= 2 megacycles\nThe amount of beauty required launch 1 ship	= 1 Millihelen', '2021-11-14 00:05:54.763138', NULL);
INSERT INTO `epigram` VALUES (157, '(1)	A sheet of paper is an ink-lined plane.\n(2)	An inclined plane is a slope up.\n(3)	A slow pup is a lazy dog.\n\nQED: A sheet of paper is a lazy dog.\n		-- Willard Espy, \"An Almanac of Words at Play\"', '2021-11-14 00:05:54.763138', NULL);
INSERT INTO `epigram` VALUES (158, '(1) Alexander the Great was a great general.\n(2) Great generals are forewarned.\n(3) Forewarned is forearmed.\n(4) Four is an even number.\n(5) Four is certainly an odd number of arms for a man to have.\n(6) The only number that is both even and odd is infinity.\n	Therefore, all horses are black.', '2021-11-14 00:05:54.763138', NULL);
INSERT INTO `epigram` VALUES (159, '(1) Alexander the Great was a great general.\n(2) Great generals are forewarned.\n(3) Forewarned is forearmed.\n(4) Four is an even number.\n(5) Four is certainly an odd number of arms for a man to have.\n(6) The only number that is both even and odd is infinity.\n\nTherefore, Alexander the Great had an infinite number of arms.', '2021-11-14 00:05:54.763138', NULL);
INSERT INTO `epigram` VALUES (160, '(1) Never draw what you can copy.\n(2) Never copy what you can trace.\n(3) Never trace what you can cut out and paste down.', '2021-11-14 00:05:54.763138', NULL);
INSERT INTO `epigram` VALUES (161, '(1) X=Y				; Given\n(2) X^2=XY			; Multiply both sides by X\n(3) X^2-Y^2=XY-Y^2		; Subtract Y^2 from both sides\n(4) (X+Y)(X-Y)=Y(X-Y)		; Factor\n(5) X+Y=Y			; Cancel out (X-Y) term\n(6) 2Y=Y			; Substitute X for Y, by equation 1\n(7) 2=1				; Divide both sides by Y\n		-- \"Omni\", proof that 2 equals 1', '2021-11-14 00:05:54.763138', NULL);
INSERT INTO `epigram` VALUES (162, '1.79 x 10^12 furlongs per fortnight -- it\'s not just a good idea, it\'s\nthe law!', '2021-11-14 00:05:54.763138', NULL);
INSERT INTO `epigram` VALUES (163, '10.0 times 0.1 is hardly ever 1.0.', '2021-11-14 00:05:54.763138', NULL);
INSERT INTO `epigram` VALUES (164, '13. ...  r-q1', '2021-11-14 00:05:54.763138', NULL);
INSERT INTO `epigram` VALUES (165, '\"355/113 -- Not the famous irrational number PI, but an incredible simulation!\"', '2021-11-14 00:05:54.763138', NULL);
INSERT INTO `epigram` VALUES (166, '7,140	pounds on the Sun\n	   97	pounds on Mercury or Mars\n	  255	pounds on Earth\n	  232	pounds on Venus or Uranus\n	   43	pounds on the Moon\n	  648	pounds on Jupiter\n	  275	pounds on Saturn\n	  303	pounds on Neptune\n	   13	pounds on Pluto\n\n		-- How much Elvis Presley would weigh at various places\n		   in the solar system.', '2021-11-14 00:05:54.763138', NULL);
INSERT INTO `epigram` VALUES (167, 'A bunch of Polish scientists decided to flee their repressive government by\nhijacking an airliner and forcing the pilot to fly them to the West.  They\ndrove to the airport, forced their way on board a large passenger jet, and\nfound there was no pilot on board.  Terrified, they listened as the sirens\ngot louder.  Finally, one of the scientists suggested that since he was an\nexperimentalist, he would try to fly the aircraft.\n	He sat down at the controls and tried to figure them out.  The sirens\ngot louder and louder.  Armed men surrounded the jet.  The would be pilot\'s\nfriends cried out, \"Please, please take off now!!!  Hurry!!!\"\n	The experimentalist calmly replied, \"Have patience.  I\'m just a simple\npole in a complex plane.\"', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (168, 'A conclusion is simply the place where someone got tired of thinking.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (169, 'A conference is a gathering of important people who singly can do nothing\nbut together can decide that nothing can be done.\n		-- Fred Allen', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (170, 'A fail-safe circuit will destroy others.\n		-- Klipstein', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (171, 'A failure will not appear until a unit has passed final inspection.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (172, '\"A fractal is by definition a set for which the Hausdorff Besicovitch\ndimension strictly exceeds the topological dimension.\"\n		-- Mandelbrot, \"The Fractal Geometry of Nature\"', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (173, 'A gangster assembled an engineer, a chemist, and a physicist.  He explained\nthat he was entering a horse in a race the following week and the three\nassembled guys had the job of assuring that the gangster\'s horse would win.\nThey were to reconvene the day before the race to tell the gangster how they\neach propose to ensure a win.  When they reconvened the gangster started with\nthe engineer:\n\nGangster: OK, Mr. engineer, what have you got?\nEngineer: Well, I\'ve invented a way to weave metallic threads into the saddle\n	  blanket so that they will act as the plates of a battery and provide\n	  electrical shock to the horse.\nG:	  That\'s very good!  But let\'s hear from the chemist.\nChemist:  I\'ve synthesized a powerful stimulant that dissolves\n	  into simple blood sugars after ten minutes and therefore\n	  cannot be detected in post-race tests.\nG:	  Excellent, excellent!  But I want to hear from the physicist before\n	  I decide what to do.  Physicist?\nPhysicist: Well, first consider a spherical horse in simple harmonic motion...', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (174, '\"A horrible little boy came up to me and said, `You know in your book\nThe Martian Chronicles?\'  I said, `Yes?\'  He said, `You know where you\ntalk about Deimos rising in the East?\'  I said, `Yes?\'  He said `No.\'\n-- So I hit him.\"\n		-- attributed to Ray Bradbury', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (175, 'A mathematician is a device for turning coffee into theorems.\n		-- P. Erdos', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (176, 'A mathematician, a doctor, and an engineer are walking on the beach and\nobserve a team of lifeguards pumping the stomach of a drowned woman.  As\nthey watch, water, sand, snails and such come out of the pump.\n	The doctor watches for a while and says: \"Keep pumping, men, you may\nyet save her!!\"\n	The mathematician does some calculations and says: \"According to my\nunderstanding of the size of that pump, you have already pumped more water\nfrom her body than could be contained in a cylinder 4 feet in diameter and\n6 feet high.\"\n	The engineer says: \"I think she\'s sitting in a puddle.\"', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (177, 'A method of solution is perfect if we can forsee from the start,\nand even prove, that following that method we shall attain our aim.\n		-- Leibniz', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (178, 'A pain in the ass of major dimensions.\n		-- C. A. Desoer, on the solution of non-linear circuits', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (179, 'A physicist is an atom\'s way of knowing about atoms.\n		-- George Wald', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (180, 'A rope lying over the top of a fence is the same length on each side.  It\nweighs one third of a pound per foot.  On one end hangs a monkey holding a\nbanana, and on the other end a weight equal to the weight of the monkey.\nThe banana weighs two ounces per inch.  The rope is as long (in feet) as\nthe age of the monkey (in years), and the weight of the monkey (in ounces)\nis the same as the age of the monkey\'s mother.  The combined age of the\nmonkey and its mother is thirty years.  One half of the weight of the monkey,\nplus the weight of the banana, is one forth as much as the weight of the\nweight and the weight of the rope.  The monkey\'s mother is half as old as\nthe monkey will be when it is three times as old as its mother was when she\nshe was half as old as the monkey will be when when it is as old as its mother\nwill be when she is four times as old as the monkey was when it was twice\nas its mother was when she was one third as old as the monkey was when it\nwas old as is mother was when she was three times as old as the monkey was\nwhen it was one fourth as old as it is now.  How long is the banana?', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (181, 'A scientific truth does not triumph by convincing its opponents and\nmaking them see the light, but rather because its opponents eventually\ndie and a new generation grows up that is familiar with it.\n		-- Max Planck', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (182, 'A sense of desolation and uncertainty, of futility, of the baselessness\nof aspirations, of the vanity of endeavor, and a thirst for a life giving\nwater which seems suddenly to have failed, are the signs in consciousness\nof this necessary reorganization of our lives.\n\nIt is difficult to believe that this state of mind can be produced by the\nrecognition of such facts as that unsupported stones always fall to the\nground.\n		-- J. W. N. Sullivan', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (183, 'A Severe Strain on the Credulity\n	As a method of sending a missile to the higher, and even to the\nhighest parts of the earth\'s atmospheric envelope, Professor Goddard\'s rocket\nis a practicable and therefore promising device. It is when one considers the\nmultiple-charge rocket as a traveler to the moon that one begins to doubt...\nfor after the rocket quits our air and really starts on its journey, its\nflight would be neither accelerated nor maintained by the explosion of the\ncharges it then might have left.  Professor Goddard, with his \"chair\" in\nClark College and countenancing of the Smithsonian Institution, does not\nknow the relation of action to re-action, and of the need to have something\nbetter than a vacuum against which to react... Of course he only seems to\nlack the knowledge ladled out daily in high schools.\n		-- New York Times Editorial, 1920', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (184, 'A sine curve goes off to infinity, or at least the end of the blackboard.\n		-- Prof. Steiner', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (185, 'A social scientist, studying the culture and traditions of a small North\nAfrican tribe, found a woman still practicing the ancient art of matchmaking.\nLocally, she was known as the Moor, the marrier.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (186, 'A statistician, who refused to fly after reading of the alarmingly high\nprobability that there will be a bomb on any given plane, realized that\nthe probability of there being two bombs on any given flight is very low.\nNow, whenever he flies, he carries a bomb with him.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (187, 'A transistor protected by a fast-acting fuse will protect the fuse by\nblowing first.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (188, 'A triangle which has an angle of 135 degrees is called an obscene triangle.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (189, 'According to convention there is a sweet and a bitter, a hot and a cold,\nand according to convention, there is an order.  In truth, there are atoms\nand a void.\n		-- Democritus, 400 B.C.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (190, 'According to the latest official figures, 43', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (191, 'of all statistics are\ntotally worthless.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (192, 'ACHTUNG!!!\n\nDas machine is nicht fur gefingerpoken und mittengrabben.  Ist easy schnappen\nder springenwerk, blowenfusen und corkenpoppen mit spitzensparken.  Ist nicht\nfur gewerken by das dummkopfen.  Das rubbernecken sightseeren keepen hands\nin das pockets.  Relaxen und vatch das blinkenlights!!!', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (193, 'Actually, the probability is 100', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (194, 'that the elevator will be going in the\nright direction.  Proof by induction:\n\nN=1.	Trivially true, since both you and the elevator only have one\n	floor to go to.\n\nAssume true for N, prove for N+1:\n	If you are on any of the first N floors, then it is true by the\n	induction hypothesis.  If you are on the N+1st floor, then both you\n	and the elevator have only one choice, namely down.  Therefore,\n	it is true for all N+1 floors.\nQED.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (195, 'After a number of decimal places, nobody gives a damn.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (196, 'After an instrument has been assembled, extra components will be found\non the bench.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (197, 'After the Children of Israel had wandered for thirty-nine years\nin the wilderness, Ferdinand Feghoot arrived to make sure that they would\nfinally find and enter the Promised Land.  With him, he brought his\nfavorite robot, faithful old Yewtoo Artoo, to carry his gear and do\nassorted camp chores.\n	The Israelites soon got over their initial fear of the robot and,\nas the months passed, became very fond of him.  Patriarchs took to\ndiscussing abtruse theological problems with him, and each evening the\nchildren all gathered to hear the many stories with which he was programmed.\nTherefore it came as a great shock to them when, just as their journey was\nending, he abruptly wore out.  Even Feghoot couldn\'t console them.\n	\"It may be true, Ferdinand Feghoot,\" said Moses, \"that our friend\nYewtoo Artoo was soulless, but we cannot believe it.  He must be properly\ninterred.  We cannot embalm him as do the Egyptians.  Nor have we wood for\na coffin.  But I do have a most splendid skin from one of Pharoah\'s own\ncattle.  We shall bury him in it.\"\n	Feghoot agreed.  \"Yes, let this be his last rusting place.\"\n	\"Rusting?\" Moses cried.  \"Not in this dreadful dry desert!\"\n	\"Ah!\" sighed Ferdinand Feghoot, shedding a tear, \"I fear you do not\nrealize the full significance of Pharoah\'s oxhide!\"\n		-- Grendel Briarton \"Through Time & Space With Ferdinand\n		   Feghoot!\"', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (198, 'After the last of 16 mounting screws has been removed from an access\ncover, it will be discovered that the wrong access cover has been removed.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (199, 'After this was written there appeared a remarkable posthumous memoir that\nthrows some doubt on Millikan\'s leading role in these experiments.  Harvey\nFletcher (1884-1981), who was a graduate student at the University of Chicago,\nat Millikan\'s suggestion worked on the measurement of electronic charge for\nhis doctoral thesis, and co-authored some of the early papers on this subject\nwith Millikan.  Fletcher left a manuscript with a friend with instructions\nthat it be published after his death; the manuscript was published in\nPhysics Today, June 1982, page 43.  In it, Fletcher claims that he was the\nfirst to do the experiment with oil drops, was the first to measure charges on\nsingle droplets, and may have been the first to suggest the use of oil.\nAccording to Fletcher, he had expected to be co-authored with Millikan on\nthe crucial first article announcing the measurement of the electronic\ncharge, but was talked out of this by Millikan.\n		-- Steven Weinberg, \"The Discovery of Subatomic Particles\"\n\nRobert Millikan is generally credited with making the first really\nprecise measurement of the charge on an electron and was awarded the\nNobel Prize in 1923.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (200, 'After years of research, scientists recently reported that there is,\nindeed, arroz in Spanish Harlem.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (201, 'Against his wishes, a math teacher\'s classroom was remodeled.  Ever\nsince, he\'s been talking about the good old dais.  His students planted a small\norchard in his honor; the trees all have square roots.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (202, 'Air is water with holes in it.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (203, 'Air pollution is really making us pay through the nose.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (204, 'Albert Einstein, when asked to describe radio, replied: \"You see, wire\ntelegraph is a kind of a very, very long cat.  You pull his tail in New\nYork and his head is meowing in Los Angeles.  Do you understand this?\nAnd radio operates exactly the same way: you send signals here, they\nreceive them there.  The only difference is that there is no cat.\"', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (205, 'Alexander Graham Bell is alive and well in New York, and still waiting\nfor a dial tone.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (206, 'Algebraic symbols are used when you do not know what you are talking about.\n		-- Philippe Schnoebelen', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (207, 'All Finagle Laws may be bypassed by learning the simple art of doing\nwithout thinking.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (208, 'All great discoveries are made by mistake.\n		-- Young', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (209, 'All great ideas are controversial, or have been at one time.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (210, 'All laws are simulations of reality.\n		-- John C. Lilly', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (211, 'All life evolves by the differential survival of replicating entities.\n		-- Dawkins', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (212, 'All power corrupts, but we need electricity.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (213, 'All science is either physics or stamp collecting.\n		-- Ernest Rutherford', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (214, 'All seems condemned in the long run to approximate a state akin to\nGaussian noise.\n		-- James Martin', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (215, 'All syllogisms have three parts, therefore this is not a syllogism.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (216, 'All the evidence concerning the universe has not yet been collected,\nso there\'s still hope.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (217, 'All theoretical chemistry is really physics; and all theoretical chemists\nknow it.\n		-- Richard P. Feynman', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (218, 'Although the moon is smaller than the earth, it is farther away.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (219, 'Although we modern persons tend to take our electric lights, radios, mixers,\netc., for granted, hundreds of years ago people did not have any of these\nthings, which is just as well because there was no place to plug them in.\nThen along came the first Electrical Pioneer, Benjamin Franklin, who flew a\nkite in a lighting storm and received a serious electrical shock.  This\nproved that lighting was powered by the same force as carpets, but it also\ndamaged Franklin\'s brain so severely that he started speaking only in\nincomprehensible maxims, such as \"A penny saved is a penny earned.\"\nEventually he had to be given a job running the post office.\n		-- Dave Barry, \"What is Electricity?\"', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (220, 'Always draw your curves, then plot your reading.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (221, 'Always leave room to add an explanation if it doesn\'t work out.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (222, 'Always think of something new; this helps you forget your last rotten idea.\n		-- Seth Frankel', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (223, 'Always try to do things in chronological order; it\'s less confusing that way.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (224, 'An age is called Dark not because the light fails to shine, but because\npeople refuse to see it.\n		-- James Michener, \"Space\"', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (225, 'An American scientist once visited the offices of the great Nobel prize\nwinning physicist, Niels Bohr, in Copenhagen.  He was amazed to find that\nover Bohr\'s desk was a horseshoe, securely nailed to the wall, with the\nopen end up in the approved manner (so it would catch the good luck and not\nlet it spill out).  The American said with a nervous laugh,\n	\"Surely you don\'t believe the horseshoe will bring you good luck,\ndo you, Professor Bohr?  After all, as a scientist --\"\nBohr chuckled.\n	\"I believe no such thing, my good friend.  Not at all.  I am\nscarcely likely to believe in such foolish nonsense.  However, I am told\nthat a horseshoe will bring you good luck whether you believe in it or not.\"', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (226, 'An anthropologist at Tulane has just come back from a field trip to New\nGuinea with reports of a tribe so primitive that they have Tide but not\nnew Tide with lemon-fresh Borax.\n		-- David Letterman', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (227, 'An architect\'s first work is apt to be spare and clean.  He knows\nhe doesn\'t know what he\'s doing, so he does it carefully and with great\nrestraint.\n	As he designs the first work, frill after frill and embellishment\nafter embellishment occur to him.  These get stored away to be used \"next\ntime.\" Sooner or later the first system is finished, and the architect,\nwith firm confidence and a demonstrated mastery of that class of systems,\nis ready to build a second system.\n	This second is the most dangerous system a man ever designs.\nWhen he does his third and later ones, his prior experiences will\nconfirm each other as to the general characteristics of such systems,\nand their differences will identify those parts of his experience that\nare particular and not generalizable.\n	The general tendency is to over-design the second system, using\nall the ideas and frills that were cautiously sidetracked on the first\none.  The result, as Ovid says, is a \"big pile.\"\n		-- Frederick Brooks, \"The Mythical Man Month\"', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (228, 'An authority is a person who can tell you more about something than you\nreally care to know.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (229, 'An economist is a man who would marry Farrah Fawcett-Majors for her money.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (230, 'An egghead is one who stands firmly on both feet, in mid-air, on both\nsides of an issue.\n		-- Homer Ferguson', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (231, 'An engineer, a physicist and a mathematician find themselves in an\nanecdote, indeed an anecdote quite similar to many that you have no doubt\nalready heard.  After some observations and rough calculations the\nengineer realizes the situation and starts laughing.  A few minutes later\nthe physicist understands too and chuckles to himself happily as he now\nhas enough experimental evidence to publish a paper.  This leaves the\nmathematician somewhat perplexed, as he had observed right away that he\nwas the subject of an anecdote, and deduced quite rapidly the presence of\nhumour from similar anecdotes, but considers this anecdote to be too\ntrivial a corollary to be significant, let alone funny.', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (232, 'And the French medical anatomist Etienne Serres really did argue that\nblack males are primitive because the distance between their navel and\npenis remains small (relative to body height) throughout life, while\nwhite children begin with a small separation but increase it during\ngrowth -- the rising belly button as a mark of progress.\n		-- S. J. Gould, \"Racism and Recapitulation\"', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (233, 'And this is a table ma\'am.  What in essence it consists of is a horizontal\nrectilinear plane surface maintained by four vertical columnar supports,\nwhich we call legs.  The tables in this laboratory, ma\'am, are as advanced\nin design as one will find anywhere in the world.\n		-- Michael Frayn, \"The Tin Men\"', '2021-11-14 00:05:54.767806', NULL);
INSERT INTO `epigram` VALUES (234, '... Another writer again agreed with all my generalities, but said that as an\ninveterate skeptic I have closed my mind to the truth.  Most notably I have\nignored the evidence for an Earth that is six thousand years old.  Well, I\nhaven\'t ignored it; I considered the purported evidence and *then* rejected\nit.  There is a difference, and this is a difference, we might say, between\nprejudice and postjudice.  Prejudice is making a judgment before you have\nlooked at the facts.  Postjudice is making a judgment afterwards.  Prejudice\nis terrible, in the sense that you commit injustices and you make serious\nmistakes.  Postjudice is not terrible.  You can\'t be perfect of course; you\nmay make mistakes also.  But it is permissible to make a judgment after you\nhave examined the evidence.  In some circles it is even encouraged.\n		-- Carl Sagan, \"The Burden of Skepticism\"', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (235, 'Any circuit design must contain at least one part which is obsolete, two parts\nwhich are unobtainable, and three parts which are still under development.', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (236, 'Any sufficiently advanced technology is indistinguishable from a rigged demo.', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (237, 'Any sufficiently advanced technology is indistinguishable from magic.\n		-- Arthur C. Clarke', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (238, 'Anyone who cannot cope with mathematics is not fully human.  At best he\nis a tolerable subhuman who has learned to wear shoes, bathe and not\nmake messes in the house.\n		-- Lazarus Long, \"Time Enough for Love\"', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (239, 'Anyone who imagines that all fruits ripen at the same time\nas the strawberries, knows nothing about grapes.\n		-- Philippus Paracelsus', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (240, '\"Anything created must necessarily be inferior to the essence of the creator.\"\n		-- Claude Shouse\n\n\"Einstein\'s mother must have been one heck of a physicist.\"\n		-- Joseph C. Wang', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (241, 'Anything cut to length will be too short.', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (242, 'Arithmetic is being able to count up to twenty without taking off your shoes.\n		-- Mickey Mouse', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (243, 'Artificial intelligence has the same relation to intelligence as\nartificial flowers have to flowers.\n		-- David Parnas', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (244, '\"As an adolescent I aspired to lasting fame, I craved factual certainty,\nand I thirsted for a meaningful vision of human life -- so I became a\nscientist.  This is like becoming an archbishop so you can meet girls.\"\n		-- Matt Cartmill', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (245, 'As far as the laws of mathematics refer to reality, they are not\ncertain, and as far as they are certain, they do not refer to reality.\n		-- Albert Einstein', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (246, 'As you will see, I told them, in no uncertain terms, to see Figure one.\n		-- Dave \"First Strike\" Pare', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (247, 'Ask five economists and you\'ll get five different explanations (six if\none went to Harvard).\n		-- Edgar R. Fiedler', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (248, 'At any given moment, an arrow must be either where it is or where it is\nnot.  But obviously it cannot be where it is not.  And if it is where\nit is, that is equivalent to saying that it is at rest.\n		-- Zeno\'s paradox of the moving (still?) arrow', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (249, 'At the heart of science is an essential tension between two seemingly\ncontradictory attitudes -- an openness to new ideas, no matter how bizarre\nor counterintuitive they may be, and the most ruthless skeptical scrutiny\nof all ideas, old and new.  This is how deep truths are winnowed from deep\nnonsense.  Of course, scientists make mistakes in trying to understand the\nworld, but there is a built-in error-correcting mechanism:  The collective\nenterprise of creative thinking and skeptical thinking together keeps the\nfield on track.\n		-- Carl Sagan, \"The Fine Art of Baloney Detection\"', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (250, 'Back in the early 60\'s, touch tone phones only had 10 buttons.  Some\nmilitary versions had 16, while the 12 button jobs were used only by people\nwho had \"diva\" (digital inquiry, voice answerback) systems -- mainly banks.\nSince in those days, only Western Electric  made \"data sets\" (modems) the\nproblems of terminology were all Bell System.  We used to struggle with\nwritten descriptions of dial pads that were unfamiliar to most people\n(most phones were rotary then.)  Partly in jest, some AT&T engineering\ntypes (there was no marketing in the good old days, which is why they were\nthe good old days) made up the term \"octalthorpe\" (note spelling) to denote\nthe \"pound sign.\"  Presumably because it has 8 points sticking out.  It\nnever really caught on.', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (251, 'Base 8 is just like base 10, if you are missing two fingers.\n		-- Tom Lehrer', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (252, 'Before Xerox, five carbons were the maximum extension of anybody\'s ego.', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (253, 'Besides the device, the box should contain:\n	* Eight little rectangular snippets of paper that say \"WARNING\"\n	* A plastic packet containing four 5/17 inch pilfer grommets and two\n		club-ended 6/93 inch boxcar prawns.\n\nYOU WILL NEED TO SUPPLY: a matrix wrench and 60,000 feet of tram cable.\n\nIF ANYTHING IS DAMAGED OR MISSING: You IMMEDIATELY should turn to your spouse\nand say: \"Margaret, you know why this country can\'t make a car that can get\nall the way through the drive-through at Burger King without a major\ntransmission overhaul?  Because nobody cares, that\'s why.\"\n\nWARNING: This is assuming your spouse\'s name is Margaret.\n		-- Dave Barry, \"Read This First!\"', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (254, 'Between infinite and short there is a big difference.\n		-- G. H. Gonnet', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (255, 'Biology grows on you.', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (256, 'Biology is the only science in which multiplication means the same thing\nas division.', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (257, 'Bistromathics is simply a revolutionary new way of understanding the\nbehavior of numbers.  Just as Einstein observed that space was not an\nabsolute, but depended on the observer\'s movement in space, and that\ntime was not an absolute, but depended on the observer\'s movement in\ntime, so it is now realized that numbers are not absolute, but depend\non the observer\'s movement in restaurants.\n		-- Douglas Adams', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (258, 'But it does move!\n		-- Galileo Galilei', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (259, 'But you who live on dreams, you are better pleased with the sophistical\nreasoning and frauds of talkers about great and uncertain matters than\nthose who speak of certain and natural matters, not of such lofty nature.\n		-- Leonardo Da Vinci, \"The Codex on the Flight of Birds\"', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (260, 'Celestial navigation is based on the premise that the Earth is the center\nof the universe.  The premise is wrong, but the navigation works.  An\nincorrect model can be a useful tool.\n		-- Kelvin Throop III', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (261, 'Chapter 2:  Newtonian Growth and Decay\n\n	The growth-decay formulas were developed in the trivial fashion by\nIsaac Newton\'s famous brother Phigg.  His idea was to provide an equation\nthat would describe a quantity that would dwindle and dwindle, but never\nquite reach zero.  Historically, he was merely trying to work out his\nmortgage.  Another versatile equation also emerged, one which would define\na function that would continue to grow, but never reach unity.  This equation\ncan be applied to charging capacitors, over-damped springs, and the human\nrace in general.', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (262, 'Chemist who falls in acid is absorbed in work.', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (263, 'Chemist who falls in acid will be tripping for weeks.', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (264, 'Chemistry is applied theology.\n		-- Augustus Stanley Owsley III', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (265, 'Chemistry professors never die, they just fail to react.', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (266, 'Congratulations!  You have purchased an extremely fine device that would\ngive you thousands of years of trouble-free service, except that you\nundoubtably will destroy it via some typical bonehead consumer maneuver.\nWhich is why we ask you to PLEASE FOR GOD\'S SAKE READ THIS OWNER\'S MANUAL\nCAREFULLY BEFORE YOU UNPACK THE DEVICE.  YOU ALREADY UNPACKED IT, DIDN\'T\nYOU?  YOU UNPACKED IT AND PLUGGED IT IN AND TURNED IT ON AND FIDDLED WITH\nTHE KNOBS, AND NOW YOUR CHILD, THE SAME CHILD WHO ONCE SHOVED A POLISH\nSAUSAGE INTO YOUR VIDEOCASSETTE RECORDER AND SET IT ON \"FAST FORWARD\", THIS\nCHILD ALSO IS FIDDLING WITH THE KNOBS, RIGHT?  AND YOU\'RE JUST NOW STARTING\nTO READ THE INSTRUCTIONS, RIGHT???  WE MIGHT AS WELL JUST BREAK THESE\nDEVICES RIGHT AT THE FACTORY BEFORE WE SHIP THEM OUT, YOU KNOW THAT?\n		-- Dave Barry, \"Read This First!\"', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (267, '\"Consider a spherical bear, in simple harmonic motion...\"\n		-- Professor in the UCB physics department', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (268, '\"Contrariwise,\" continued Tweedledee, \"if it was so, it might be, and\nif it were so, it would be; but as it isn\'t, it ain\'t.  That\'s logic!\"\n		-- Lewis Carroll, \"Through the Looking Glass\"', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (269, '\"Deep\" is a word like \"theory\" or \"semantic\" -- it implies all sorts of\nmarvelous things.  It\'s one thing to be able to say \"I\'ve got a theory\",\nquite another to say \"I\'ve got a semantic theory\", but, ah, those who can\nclaim \"I\'ve got a deep semantic theory\", they are truly blessed.\n		-- Randy Davis', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (270, 'Did you hear that there\'s a group of South American Indians that worship\nthe number zero?\n\nIs nothing sacred?', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (271, 'Did you hear that two rabbits escaped from the zoo and so far they have\nonly recaptured 116 of them?', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (272, 'Did you know that if you took all the economists in the world and lined\nthem up end to end, they\'d still point in the wrong direction?', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (273, 'Dimensions will always be expressed in the least usable term, convertible\nonly through the use of weird and unnatural conversion factors.  Velocity,\nfor example, will be expressed in furlongs per fortnight.', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (274, 'Dinosaurs aren\'t extinct.  They\'ve just learned to hide in the trees.', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (275, 'Do molecular biologists wear designer genes?', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (276, 'Duct tape is like the force.  It has a light side, and a dark side, and\nit holds the universe together ...\n		-- Carl Zwanzig', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (277, 'E = MC ** 2 +- 3db', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (278, 'Earl Wiener, 55, a University of Miami professor of management science,\ntelling the Airline Pilots Association (in jest) about 21st century aircraft:\n\n	\"The crew will consist of one pilot and a dog.  The pilot will\n	nurture and feed the dog.  The dog will be there to bite the\n	pilot if he touches anything.\n		-- Fortune, Sept. 26, 1988\n		   [the *magazine*, silly!]', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (279, 'Economics is extremely useful as a form of employment for economists.\n		-- John Kenneth Galbraith', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (280, 'Economists can certainly disappoint you.  One said that the economy would\nturn up by the last quarter.  Well, I\'m down to mine and it hasn\'t.\n		-- Robert Orben', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (281, 'Economists state their GNP growth projections to the nearest tenth of a\npercentage point to prove they have a sense of humor.\n		-- Edgar R. Fiedler', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (282, 'Electricity is actually made up of extremely tiny particles, called\nelectrons, that you cannot see with the naked eye unless you have been\ndrinking.  Electrons travel at the speed of light, which in most American\nhomes is 110 volts per hour.  This is very fast.  In the time it has taken\nyou to read this sentence so far, an electron could have traveled all the\nway from San Francisco to Hackensack, New Jersey, although God alone knows\nwhy it would want to.\n\nThe five main kinds of electricity are alternating current, direct current,\nlightning, static, and European.  Most American homes have alternating\ncurrent, which means that the electricity goes in one direction for a while,\nthen goes in the other direction.  This prevents harmful electron buildup in\nthe wires.\n		-- Dave Barry, \"The Taming of the Screw\"', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (283, 'Elegance and truth are inversely related.\n		-- Becker\'s Razor', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (284, 'Elliptic paraboloids for sale.', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (285, 'Entropy isn\'t what it used to be.', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (286, 'Entropy requires no maintenance.\n		-- Markoff Chaney', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (287, 'Enzymes are things invented by biologists that explain things which\notherwise require harder thinking.\n		-- Jerome Lettvin', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (288, 'Eureka!\n		-- Archimedes', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (289, 'Every little picofarad has a nanohenry all its own.\n		-- Don Vonada', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (290, 'Every nonzero finite dimensional inner product space has an orthonormal basis.\n\nIt makes sense, when you don\'t think about it.', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (291, 'Every paper published in a respectable journal should have a preface by\nthe author stating why he is publishing the article, and what value he\nsees in it.  I have no hope that this practice will ever be adopted.\n		-- Morris Kline', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (292, 'Everyone knows that dragons don\'t exist.  But while this simplistic\nformulation may satisfy the layman, it does not suffice for the scientific\nmind.  The School of Higher Neantical Nillity is in fact wholly unconcerned\nwith what ____x08x08x08x08does exist.  Indeed, the banality of existence has been\nso amply demonstrated, there is no need for us to discuss it any further\nhere.  The brilliant Cerebron, attacking the problem analytically,\ndiscovered three distinct kinds of dragon: the mythical, the chimerical,\nand the purely hypothetical.  They were all, one might say, nonexistent,\nbut each nonexisted in an entirely different way ...\n		-- Stanislaw Lem, \"Cyberiad\"', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (293, 'Everything should be made as simple as possible, but not simpler.\n		-- Albert Einstein', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (294, 'Everything that can be invented has been invented.\n		-- Charles Duell, Director of U.S. Patent Office, 1899', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (295, 'Everything you\'ve learned in school as \"obvious\" becomes less and less\nobvious as you begin to study the universe.  For example, there are no\nsolids in the universe.  There\'s not even a suggestion of a solid.\nThere are no absolute continuums.  There are no surfaces.  There are no\nstraight lines.\n		-- R. Buckminster Fuller', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (296, 'Evolution is as much a fact as the earth turning on its axis and going around\nthe sun.  At one time this was called the Copernican theory; but, when\nevidence for a theory becomes so overwhelming that no informed person can\ndoubt it, it is customary for scientists to call it a fact.  That all present\nlife descended from earlier forms, over vast stretches of geologic time, is\nas firmly established as Copernican cosmology.  Biologists differ only with\nrespect to theories about how the process operates.\n		-- Martin Gardner, \"Irving Kristol and the Facts of Life\".', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (297, 'Experience varies directly with equipment ruined.', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (298, 'Experiments must be reproducible; they should all fail in the same way.', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (299, 'Extraordinary claims demand extraordinary proof.  There are many examples\nof outsiders who eventually overthrew entrenched scientific orthodoxies,\nbut they prevailed with irrefutable data.  More often, egregious findings\nthat contradict well-established research turn out to be artifacts.  I have\nargued that accepting psychic powers, reincarnation, \"cosmic consciousness,\"\nand the like, would entail fundamental revisions of the foundations of\nneuroscience.  Before abandoning materialist theories of mind that have paid\nhandsome dividends, we should insist on better evidence for psi phenomena\nthan presently exists, especially when neurology and psychology themselves\noffer more plausible alternatives.\n		-- Barry L. Beyerstein, \"The Brain and Consciousness:\n		   Implications for Psi Phenomena\".', '2021-11-14 00:05:54.768473', NULL);
INSERT INTO `epigram` VALUES (300, 'Factorials were someone\'s attempt to make math LOOK exciting.', '2021-11-14 00:05:54.768473', NULL);

-- ----------------------------
-- Table structure for hibernate_sequence
-- ----------------------------
DROP TABLE IF EXISTS `hibernate_sequence`;
CREATE TABLE `hibernate_sequence`  (
  `next_val` bigint(0) NULL DEFAULT NULL
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of hibernate_sequence
-- ----------------------------
INSERT INTO `hibernate_sequence` VALUES (301);

SET FOREIGN_KEY_CHECKS = 1;
